### ISSUE TITLE
Implement remaining endpoints that are missing from `artemis_client`

### ISSUE THREAD

**Issue by Luro02** [kit-sdq/artemis4j#40] opened 2023-12-21 10:11 UTC
There are a few endpoints missing (especially those for text assignments): https://github.com/kit-sdq/artemis_client

**Comment by dfuchss** [comment] 2024-07-16 21:37
Duplicate of https://github.com/kit-sdq/artemis4j/issues/73

**Closed by dfuchss** 2024-07-16 21:37 UTC
